#Inhalt#Anzahl Geschenk 1:
inhalt1:
  - IRON_INGOT#8
  - GOLD_INGOT#4
  - DIAMOND#1
  - QUARTZ#16
  - EMERALD#2


radius: 10
geschenke: 10
#Zeit zwischen drops (wenn leer: 5 Sekunden)
pause: 3
#Nachricht bei drop (kann leer sein!)
dropnachricht: